require("user.plugins-setup")

require("user.core.colorscheme")
require("user.core.options")
require("user.core.keymaps")

require("user.plugins.cmp")
require("user.plugins.lsp")
require("user.plugins.comment")
require("user.plugins.lualine")
require("user.plugins.gitsigns")
require("user.plugins.nvim-tree")
require("user.plugins.telescope")
require("user.plugins.tresitter")
require("user.plugins.autopairs")
require("user.plugins.dashboard")
require("user.plugins.colorizer")
require("user.plugins.bufferline")
require("user.plugins.indent-blankline")

require("user.plugins.lsp.mason")
require("user.plugins.lsp.lspsaga")
require("user.plugins.lsp.null-ls")
require("user.plugins.lsp.lspconfig")
