require("user.base")
require("user.highlights")
require("user.maps")
require("user.setup-plugins")

require("user.plugins.alpha")
require("user.plugins.autopairs")
require("user.plugins.bufferline")
require("user.plugins.cmp")
require("user.plugins.colorizer")
require("user.plugins.comment")
require("user.plugins.gitsigns")
require("user.plugins.harpoon")
require("user.plugins.indent-blankline")
require("user.plugins.kanagawa")
require("user.plugins.lspconfig")
require("user.plugins.lspkind")
require("user.plugins.lspsaga")
require("user.plugins.lualine")
require("user.plugins.mason")
require("user.plugins.neotree")
-- require("user.plugins.noice")
require("user.plugins.notify")
require("user.plugins.null-ls")
require("user.plugins.peek")
require("user.plugins.presence")
require("user.plugins.surround")
require("user.plugins.telescope")
require("user.plugins.treesitter")
require("user.plugins.trouble")

vim.cmd([[colorscheme tokyonight]])
-- vim.cmd([[colorscheme gruvbox]])
